format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$username \
$hostname \
$time \
$line_break\
$status\
$character\
"""

add_newline = true

[directory]
format = '[$read_only$truncation_symbol$path](fg:red)'
# home_symbol = "~"
truncation_symbol = '.../'
# truncation_length = 3
# read_only = 'x '
# read_only_style = ''

[git_branch]
format = '[ $branch](fg:green)'

[git_status]
format = "[ $all_status$ahead_behind](fg:green)"

[fill]
symbol = ' '
style = 'fg:current_line'

[status]
disabled = false
symbol = ''
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
signal_symbol = ''

[cmd_duration]
min_time = 500
format = '[$duration ](fg:cyan)'

[time]
format = '[$time](fg:purple)'
time_format = '%H:%M'
disabled = false

[hostname]
ssh_only = false
format = '[$hostname](fg:blue)'

[username]
format = '[$user](fg:yellow)'
show_always = true
